docs/docs/async-support.md, docs/docs/help.md, docs/docs/motivation.md, docs/docs/proposals/cbv.md, docs/docs/proposals/models.md, docs/docs/proposals/responses.md, docs/docs/tutorial/authentication.md, docs/docs/tutorial/body.md, docs/docs/tutorial/index.md, docs/docs/tutorial/path-params.md, docs/docs/tutorial/query-params.md, docs/docs/tutorial/response-schema.md, docs/docs/tutorial/routers.md, docs/docs/tutorial/versioning.md
Fixed minor typos and spelling errors in documentation.
I didn't want to change anything more serious in the text, but I'm happy to do some deeper editing for clarity/style if it's useful.
=> docs: fix spelling errors in documentation.

docs/docs/async-support.md, docs/docs/help.md, docs/docs/tutorial/authentication.md, docs/docs/tutorial/body.md
=> :memo: fix a few more typos in docs

ninja/openapi/schema.py
=> Add response schema for swagger

ninja/openapi/schema.py, ninja/operation.py, tests/test_response_multiple.py
This implements multiple response schemas using the dict approach discussed in issue #16.
=> Implement multiple response schemas

docs/docs/index.md
=> Django Ninja

ninja/main.py, ninja/openapi/urls.py
Forgot to remove type checking conditions from code coverage
=> Increase code coverage

docs/src/tutorial/query/code010.py, ninja/signature/details.py, tests/test_docs/test_query.py, tests/test_lists.py
=> Allow collection fields to be identified when an alias is used

ninja/operation.py, ninja/testing/client.py, tests/test_app.py
This PR adds support for streaming responses, specifically FileResponse and StreamingHttpResponse. Tests included. I didn't bother creating an issue first, please let me know if you need me to create an issue.
=> Add support for streaming responses (FileResponse, StreamingHttpResponse)

docs/docs/motivation.md
See: https://forum.djangoproject.com/t/asynchronous-orm/5925
Django ORM is not `async` compatible as of 3.2 and *may* be by 4.0 or 4.1
=> Update the docs that Django ORM is not async compatible as of 3.2

docs/docs/tutorial/config-pydantic.md, docs/mkdocs.yml
Documentation which may resolve #136 create_schema with custom Schema base model
=> Documentation to resolve #136

.github/workflows/test_full.yml, ninja/schema.py, ninja/testing/client.py
[Django Stubs 1.9.0](https://github.com/typeddjango/django-stubs/compare/1.8.0...1.9.0), released on 2021-09-04, broke the Mypy build.
=> Github build broken

.coveragerc, ninja/main.py, ninja/openapi/schema.py, ninja/orm/fields.py, ninja/signature/details.py, ninja/testing/client.py, ninja/utils.py, tests/test_auth.py, tests/test_openapi_schema.py, tests/test_query_schema.py, tests/test_request.py, tests/test_test_client.py
Turn on branch coverage and add test cases to cover all branches.
=> Add test coverage for branches

tests/test_auth_routers.py, tests/test_exceptions.py
I found two tests that could use pytest's parametrize function. As it's a good practice i optimized them.
=> Optimize tests

docs/docs/help.md, docs/docs/tutorial/authentication.md, docs/docs/tutorial/body.md, docs/docs/tutorial/config-pydantic.md, docs/docs/tutorial/csrf.md, docs/docs/tutorial/django-pydantic-create-schema.md, docs/docs/tutorial/django-pydantic.md, docs/docs/tutorial/errors.md, docs/docs/tutorial/form-params.md, docs/docs/tutorial/index.md, docs/docs/tutorial/operation_params.md, docs/docs/tutorial/pagination.md, docs/docs/tutorial/path-params.md, docs/docs/tutorial/query-params.md, docs/docs/tutorial/request-parsers.md, docs/docs/tutorial/response-renderers.md, docs/docs/tutorial/response-schema.md, docs/docs/tutorial/versioning.md, docs/src/tutorial/form/code01.py, docs/src/tutorial/form/code02.py, docs/src/tutorial/form/code03.py, tests/test_docs/test_form.py
Closes #128, since other issues there, were already dealt with via #226
=> Document how to handle empty form fields.

ninja/openapi/schema.py, tests/test_openapi_schema.py, tests/test_wraps.py
=> Fix form schema single param

docs/docs/proposals/cbv.md
I've encountered document with formatting issues [here](https://django-ninja.rest-framework.com/proposals/cbv/). This is my attempt to fix it.
=> Fix code formatting in docs proposals/cbv.md

docs/docs/tutorial/index.md
=> Add clarification to the api_operation method

docs/docs/tutorial/urls.md, docs/mkdocs.yml
=> Add url reversal docs

docs/docs/tutorial/management-commands.md, docs/mkdocs.yml, ninja/management/commands/export_openapi_schema.py, tests/test_export_openapi_schema.py
Hi!
I want to add a basic management command to export OpenAPI schema.
=> Export OpenAPI schema management cmd

docs/docs/tutorial/response-schema.md
=> Fix a typing issue

docs/docs/tutorial/pagination.md, docs/docs/tutorial/response-schema.md, ninja/pagination.py, ninja/params_functions.py, tests/env-matrix/README.md, tests/test_async.py
=> Fix a few typos

ninja/signature/details.py, tests/test_signature_details.py
=> Handle class instances in `signature.details.is_collection_type`

.pre-commit-config.yaml, mypy.ini, ninja/orm/factory.py, ninja/testing/client.py
Running `pre-commit` is otherwise broken due to: https://github.com/psf/black/issues/2964
=> Upgrade versions of pre-commit hooks

README.md, docs/docs/index.md, docs/docs/tutorial/alternative-api-docs.md, docs/docs/tutorial/index.md, docs/mkdocs.yml
=> Update Redoc related documents

docs/docs/tutorial/response-schema.md
Added quick example for multiple items  [per @vitalik  comment on #499](https://github.com/vitalik/django-ninja/issues/499#issuecomment-1178650318B)
=> Added mutiple items example

ninja/main.py
Registry validation error message said "distinguish them you need to set either unique version or url_namespace" when it should have said *urls_namespace*.
=> Fix url_namespace -> urls_namespace msg

docs/docs/motivation.md
Some links lead to 404 errors in the documentation
=> Shuffle doc files around

docs/mkdocs.yml
Here is the doc. https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
=> Set up doc search

docs/docs/guides/async-support.md
Some reformatting was done by the markdownlint vs code extension, hope that's not a problem.
=> Include information about Django 4.1 async ORM

docs/docs/reference/operations-parameters.md, ninja/main.py, ninja/openapi/schema.py, ninja/operation.py, ninja/params.py, ninja/params_functions.py, ninja/router.py, tests/test_openapi_params.py, tests/test_openapi_schema.py
Implemented options `examples, example, deprecated, include_in_schema` for param functions. 
Also `openapi_extra` option added on routes.
=> feat: openapi schema improvements

ninja/pagination.py, ninja/testing/client.py
The typing for `**kwargs` shouldn't be a dict (unless each argument actually *should* be a dictionary, which isn't often the case).
Let's fix it :)
=> Fix kwargs typing

ninja/pagination.py
This pr closes [issue 750](https://github.com/vitalik/django-ninja/issues/750).
=> fix: paginate typo

ninja/responses.py, tests/test_response.py
ref: https://github.com/vitalik/django-ninja/issues/717
=> feat: add JSON encoding support for IPv4Address and IPv6Address

docs/docs/guides/authentication.md
from ninja.security import django_auth_superuser
=> authenticate a superuser

docs/docs/motivation.md
Fixes spelling mistake in the motivation documentation.
Great library!
=> Fix spelling error in motivation documentation

docs/docs/motivation.md
These seem to be old links, I think I got the new URLs correct.
=> Fix links on `Motivation` page of Docs.

ninja/openapi/schema.py, tests/test_openapi_extra.py
Update OpenAPI from 3.0.2 to 3.1.0.
Fixes #921
=> Update OpenAPI version

.gitignore
Found in `git status` whilst running test suite locally.
=> Git ignore coverage.xml file

ninja/files.py, ninja/orm/fields.py
Replaces `general_plain_validator_function` with `with_info_plain_validator_function`.
Fixes #920
=> Replace deprecated Pydantic method

ninja/orm/fields.py
Seems like it fixes https://github.com/vitalik/django-ninja/issues/881 but there might be other implications that I don't see
=> Add UUID to supported fields

docs/docs/guides/authentication.md, docs/docs/guides/routers.md, docs/docs/tutorial/step3.md, docs/src/tutorial/authentication/code002.py, tests/test_docs/test_auth.py
Fix some minor spelling errors and tweak some markup in the documentation.
=> Minor documentation tweaks

docs/docs/guides/testing.md, docs/mkdocs.yml
Adding some very basic testing documentation to make it clear, at a minimum, a TestClient is available. 
I don't feel I understand the TestClient's design intentions to go much deeper than this, but I hope this, at least, presents a small guidepost for people looking to write their first test. 
Open questions:
- Is it possible to test an API directly rather than via a router? In my personal work, I was unable to do so. (see: https://github.com/vitalik/django-ninja/issues/1017)
- What if any recommendations should be made for mocking authentication? It's currently possible to mock auth via a combination of patching and setting dummy credentials (see: https://github.com/vitalik/django-ninja/issues/403) but the implementation depends on the auth method being used and the code under test. …
=> Add basic testing documentation

ninja/orm/fields.py, tests/test_orm_schemas.py
Fixes #1186: Adds support for a missing field and corresponding unit test.
=> Add ORM support for SmallAutoField

docs/docs/guides/response/pagination.md
fix spelling error in pagination.md
=> fix spelling error in pagination.md

docs/docs/guides/testing.md
It was not clear how to test endpoints with a user
=> Adding docs how to add a user in a test

docs/docs/guides/routers.md
As mentioned in this thread: https://github.com/vitalik/django-ninja/issues/1055, and it took me a while to find that thread, so thought it was alright to update the docs to reflect how this could be done with a working example.
=> Updated docs for url parameters in nested routers

ninja/patch_dict.py
=> PatchDict typing enhancement

docs/docs/guides/input/file-params.md
Fixes a minor typo of reasons in link text
=> Fix minor typo in Update file-params.md

docs/docs/whatsnew_v1.md
Fix a typo in the word "series".
=> fix typo in "whatsnew_v1.md"
