vitalik/django-ninja

docs/docs/tutorial/response-schema.md, docs/docs/tutorial/routers.md
Fixed some typos, and a dead link.
=> :memo: fix typos in documentation

ninja/main.py
Under nested namespace, we only return last part for register, and use full namespace todo `reverse`.
=> fix reverse error under nested namespace

docs/src/tutorial/path/code01.py, docs/src/tutorial/path/code02.py
In the `path-params` part of the tutorial I'm pretty it should be `api` decorator instead of `app`.
=> fixed two docs typos

pyproject.toml
Since `django-ninja` supports Python 3.6+, let's remove unsupported classifier
=> Remove Python :: 3.5 classifier

ninja/openapi/schema.py, ninja/orm/factory.py, ninja/router.py, ninja/signature/details.py
Starting from Python 3.6+ dictionaries are ordered by default
=> Replace OrderedDict with dict

ninja/openapi/schema.py, tests/test_response_multiple.py
This is related to Issue #147.
This PR replaces the status code description with the description in the `http.client` library. This is the same way Django finds HTTP status code descriptions ([Django source](https://github.com/django/django/blob/225d96533a8e05debd402a2bfe566487cc27d95f/django/http/response.py#L133)).
Looking into allowing custom status descriptions, there seems to be no way to override the description Django uses, making the ability to change the description in the OpenAPI schema useless and could encourage incorrect OpenAPI specifications. Feel free to correct me if I'm wrong though!
=> Grab http status code phrases from http library

mypy.ini, ninja/compatibility/util.py, ninja/main.py
in particular, importing the `Decorator` in `main.py` from the wrong module makes e.g. `api.get()` get interpreted as an untyped decorator in apps with mypy `strict` mode, resulting in `Untyped decorator makes function "my_view" untyped`
=> add (and fix) no_implicit_reexport for mypy

ninja/testing/client.py, tests/test_test_client.py
I missed this method when I try to write a test for my project.
=> Implements fake build_absolute_uri on test client

docs/docs/tutorial/authentication.md, docs/src/tutorial/authentication/bearer02.py, ninja/operation.py, tests/test_auth.py
This small patch catches all exceptions raised by the authentication callback and lets `on_exception` handle them.
This allows us to raise custom exceptions and return different responses depending on what went wrong during authentication.
Ref: #141 
I also added response body checking to `test_auth` since we need to check that the custom response comes through.
=> Handle custom exceptions in _run_authentication

ninja/main.py, ninja/router.py, ninja/types.py
unfortunately the alias doesn't work
see e.g. https://github.com/python/mypy/issues/3924
```python
from typing import Any, Callable, TypeVar
TCallable = TypeVar("TCallable", bound=Callable[..., Any])
Decorator = Callable[[TCallable], TCallable]
def direct() -> Callable[[TCallable], TCallable]:
...
def alias() -> Decorator[TCallable]:
...
def half_alias() -> Decorator:
...
reveal_type(direct())
reveal_type(alias())
reveal_type(half_alias())
```
```bash
$ mypy --strict test.py
test.py:15:21: error: Missing type parameters for generic type "Decorator"
test.py:19:13: note: Revealed type is "def [TCallable <: def (*Any, **Any) -> Any] (TCallable`-1) -> TCallable`-1"
test.py:20:13: note: Revealed type is "def (<nothing>) -> <nothing>"
test.py:21:13: note: Revealed type is "def (Any) -> Any" …
```
=> inline the Decorator type alias

ninja/main.py, ninja/router.py, tests/test_inheritance_routers.py
After a router is attached to an api, attaching further routers to the attached router fails.
=> Fix add_router() to router already attached to API

docs/docs/releases.md
The releases link is not formatted as Markdown link. This PR fixes that.
=> Format releases URL as a link

ninja/signature/details.py, tests/main.py, tests/test_query.py
=> Allow dot in query name alias

docs/docs/proposals/v1.md
Hello, I found some typo in proposals/v1.md doc and fixed it 😄 
1. `intorducing` -> `introducing`
2. `initally` -> `initially`
Thank you 😄
=> Fix: Fix typo in proposals/v1.md doc

docs/docs/tutorial/pagination.md
It is defined as "page_size" in code but doc says it's "per_page".
=> Doc fix: per_page to page_size

ninja/operation.py, pyproject.toml
Add pydantic 1.9.0 version support
https://pydantic-docs.helpmanual.io/changelog/
=> Pydantic 1.9.0 support

ninja/testing/client.py, tests/test_test_client.py
I made some incorrect assumptions about the `TestClient` arguments when I tried to use it after using Djangos and DRFs test clients. These commits tries to improve using it:
* Use the NinjaJsonEncoder when serializing the json-parameter to allow passing a Schema directly to the TestClient-methods, and also serializing datetime objects using the parent DjangoJSONEncoder.
E.g. `client.post('/my-path/', json=SomeSchema(foo=1, bar=2))`, `client.post('/my-path/', json={'now': timezone.now()})`
* Allow passing serialized json as the body-argument for TestClient request-methods for better consistency with the Django test client
=> Improve TestClient json argument-serialization

ninja/openapi/schema.py, tests/test_enum.py, tests/test_openapi_schema.py, tests/test_with_django/schema_fixtures/test-multi-cookie.json, tests/test_with_django/schema_fixtures/test-multi-header.json, tests/test_with_django/schema_fixtures/test-multi-path.json, tests/test_with_django/schema_fixtures/test-multi-query.json
This pull request fixes the visualization of params descriptions in swagger docs #326 #322 
The solution approach was to copy the description obtained from the schema to the top-level param dictionary.
=> Fix params descriptions visualization in swagger ui

docs/docs/tutorial/response-schema.md, ninja/orm/metaclass.py, ninja/schema.py, tests/test_schema.py
Fixes #291 (even though it was closed) and fixes #250 and adds in new functionality to allow calculated fields via `resolve_` static methods on the response schema class.
Includes tests and docs.
=> Smarter schema that handles dotted aliases and resolver methods

ninja/compatibility/util.py, ninja/signature/details.py, tests/test_openapi_schema.py
@vitalik This MR adds support for defining a request body as a union of two schemas. 
Prior to this change, a payload with the union type would be incorrectly classified as a query parameter, and fail to appear within the list of components defined in the OpenAPI schema
=> Add support for union type in payload

ninja/operation.py
Hi. 
This is a small change to get the first key faster.
```python
import timeit
print(timeit.timeit('next(iter(response_models))', setup='response_models = {200: "blabla"}'))
print(timeit.timeit('list(response_models.keys())[0]', setup='response_models = {200: "blabla"}'))
```
=> First key derivation optimization

.pre-commit-config.yaml, CONTRIBUTING.md, pyproject.toml
Add a pre-commit config to allow contributors to create a git hook that will check their code _before_ committing, avoiding the common cycle of: push, fix styles, push, fix types, push...
=> pre-commit config

ninja/main.py, ninja/router.py, ninja/utils.py, tests/test_router_path_params.py, tests/test_utils.py
This PR proposes and implements the following.
Adding path params when including the router (e.g. `app.add_router("/item/{item_id}", router)` does not work as expected. The test client and the actual application routing logic cannot find the endpoint.
Using `app.add_router("/item/{item_id}", router)` will allow the user to treat `item_id` as a path parameter if they so choose.
This change should not break any existing behavior.
With FastAPI, you can do something like this
```python
api = FastAPI()
router = Router(prefix="item/{item_id}/")
@router.get("/metadata")
def get_item_metadata(item_id: str):
return item_id
api.include_router(router)
```
Then you could do the following and expect output:
```shell
curl localhost:8000/item/my_item/metadata
my_item
```
This change will allow a similar …
=> Allow path parameters to be specified at router level

ninja/operation.py
Really just a few typing improvements, but also has a small optimisation:
Currently every operation builds the list of allowed_methods, even though this is only used in the case that no methods match. Just build this list in the much more infrequent case of this occurring.
=> Small optimization and typing improvements

ninja/files.py
Having uploaded file inherit from bytes causes inaccurate typing.
This PR fixes the typing issues by:
- having UploadedFile inherit from Django's UploadedFile instead of bytes
- adding a __modify_schema__ class method so that it appears the same way as a `bytes` type would in schemas.
=> UploadedFile inherit from Django's UploadedFile

CONTRIBUTING.md
Mypy is run in `make lint` but is not specified in the contributing docs.
This PR makes it clearer that mypy is required as part of the linting process.
=> Specify mypy in CONTRIBUTING.md

ninja/orm/metaclass.py, tests/test_orm_metaclass.py
Makes it a bit easier for newbies like me.
Signed-off-by: Sebastian Wagner <sebastian@inter.link>
=> ConfigError: ModelSchema classes requires a 'Config' subclass

ninja/testing/client.py, tests/test_response_cookies.py
Give an access to the attributes of the Django response wrapped inside the test response of Ninja by providing a `__getattr__` method that it called when an attribute lookup has not found the attribute of the test response.
=> Access to test response attributes

docs/docs/tutorial/errors.md, ninja/errors.py, ninja/operation.py
This PR adjusts authentication validation to throw an exception when authentication fails, particularly when using multiple authenticators. With this, developers will have greater flexibility to work with different returns.
When working with multiple authenticators `auth=[BasicAuth(), ApiKey()]` it was not possible to change the return, which by default is `{"detail": "Unauthorized"}`. Now through the [Handling errors](https://django-ninja.rest-framework.com/tutorial/errors/) I can override the default exception handlers.
=> Improves authentication validation to throw an exception

ninja/main.py
Hi, this error was appearing when I had `client = TestClient(api)` (imported api) in 2 tests. Fixing it by creating only one shared test client.
It took me a while to guess that making a TestClient implicitly creates a NinjaAPI, so I hope this clarification to the error message will be helpful.
It would be nice to get a stack trace here too as this is all I see
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <ninja.main.NinjaAPI object at 0x137ef20d0>
def _validate(self) -> None:
from ninja.security import APIKeyCookie
skip_registry = os.environ.get("NINJA_SKIP_REGISTRY", False)
if (
not skip_registry
and self.urls_namespace in NinjaAPI._registry
and not debug_server_url_reimport()
):
msg = [ …
```
=> Add TestClient note to multiple APIs warning

ninja/security/__init__.py, ninja/security/session.py, tests/test_auth.py
I have some use cases where some APIs are only for some privileged root user and it quite helpful to have an helper to add this extra security.
Let me know
=> [feat] add superuser session authentication only

docs/docs/tutorial/urls.md, ninja/operation.py, tests/demo_project/someapp/api.py, tests/test_django_models.py
Fixes #355
Huh, I had assumed this is how it worked anyway.
=> Implement implicit reverse url name generation

docs/docs/tutorial/urls.md, ninja/main.py, ninja/router.py
Seems like having access to the router could also be useful when you fall back to configuring the url_name (building the url name by tags, or whatever)
=> Also pass the router to `get_operation_url_name`

ninja/errors.py
This pull request is pretty simple, it just adds the AuthenticationError exception class to __all__ so it can be imported into projects. I'm sorry I didn't do this in pull request #454.
=> Declare the AuthenticationError exception class in __all__

pyproject.toml
Hi there,
It seems that this project doesn't have repository url configured.
This PR aims to solve this issue.
So when this Pull Request is merged we can get a PyPi Github Icon
<details>
<summary>Example Badge ( taken from poetry )</summary>
</details>
=> [ `Enchancement` ] : Add repository url in `pyproject.toml`

ninja/management/commands/export_openapi_schema.py
openapi generation shuffles the keys around from time to time. 
When the schema is in VCS, on every generation a huge changeset is created.
This pr adds a `--sorted` flag to sort the object keys on json export
=> add --sorted flag to export_openapi_schema

ninja/openapi/schema.py, tests/test_openapi_schema.py
When specifying a renderer with a custom media type, the generated schema docs don't reflect the media type header.
It always returns application/json.
This patch uses the media_type from the custom renderer to render the response schema media type
=> Set correct media type in docs for custom renderer

.github/workflows/publish.yml, .github/workflows/test_full.yml
python 3.6 isn't available anymore on gh-actions.
- removes version 3.6
- adds version 3.11
=> remove python 3.6

ninja/utils.py
This is a quick take on #623 
https://docs.python.org/3/library/inspect.html#inspect.stack
inspect.stack(context=1) adds context lines to the stackframe.
using context=0 file loads can be avoided and might bring an improved startup time already
=> remove context from inspect.stack

docs/docs/proposals/index.md
The [proposals section](https://django-ninja.rest-framework.com/proposals/) in the docs references [Schemas from Django models](https://django-ninja.rest-framework.com/proposals/models), which seems to have been implemented already. 
This PR removes the broken link.
=> [Docs] remove broken link

docs/docs/tutorial/other/crud.md
Add a recipe for handling the file uploads.
=> Add a recipe for handling the file uploads

.pre-commit-config.yaml, ninja/main.py, ninja/openapi/schema.py, ninja/params_models.py, ninja/router.py, ninja/security/http.py, tests/test_auth_inheritance_routers.py, tests/test_docs/test_body.py, tests/test_docs/test_form.py, tests/test_docs/test_path.py, tests/test_docs/test_query.py, tests/test_export_openapi_schema.py, tests/test_openapi_schema.py, tests/test_test_client.py
This PR fixes #666 and adds support to the inheritance of auth in routers.
=> Fix #666: Support auth inheritance for routers

ninja/management/commands/export_openapi_schema.py, tests/test_export_openapi_schema.py
Closes https://github.com/vitalik/django-ninja/issues/381
Currently, if you don't have a NinjaAPI instance at the URL `/api/`, then the `export_openapi_schema` command will fail with an opaque error message. This PR improves the error message in that scenario, telling the user to pass the path to the API using the `--api` flag.
=> improve error message in export_openapi_schema

docs/docs/guides/input/filtering.md, docs/docs/guides/input/query-params.md, docs/mkdocs.yml, ninja/__init__.py, ninja/filter_schema.py, tests/test_filter_schema.py
The documentation section [explains](https://django-ninja.rest-framework.com/guides/input/query-params/#using-schema) how to add query parameters to an API handler encapsulated into a separate schema:
```python
class Filters(Schema):
limit: int = 100
offset: int = None
query: str = None
category__in: List[str] = Field(None, alias="categories")
@api.get("/filter")
def events(request, filters: Filters = Query(...)):
return {"filters": filters.dict()}
```
That is helpful already as it:
1. Takes care of documenting and validating the fields in the schema;
2. Provides an explicit separation of concerns to the parameters of the method.
However, it seems that when it comes to actually applying those filters in the API handler, the developer is left on their own and will probably have to do …
=> Somewhat advanced filtering with FilterSchema

ninja/operation.py, ninja/router.py, tests/demo_project/demo/urls.py, tests/test_reverse.py
A pretty glaring shortcoming is that it is impossible to reverse URLs that have been registered with same path, but different operations.
Using the same path for different operations is a pretty common pattern. It is even used throughout Ninja's documentation.
@router.get("/{identifier}")
def detail(request, identifier: str):
return "ok"
@router.put("/{identifier}")
def update(request, identifier: str, data: Policy):
return "ok"
The above is perfectly valid, but reversing `update` using `django.urls.reverse()` will result in a `NoReverseMatch` error.
This commit is an attempt at solving the issue. N.B. I am not familiar with the internals of Ninja. This is just an experiment.
=> Allow reversing URLs with multiple operations.

ninja/signature/details.py, tests/test_openapi_schema.py
The Python 3.10+ syntax of creating a union or optional type (with `str | int`), results in a different type than using the pre-Python 3.10 syntax (`Union[str, int]`).
```pycon
>>> from typing import Optional, Union, get_origin
>>> get_origin(Union[int, str])
typing.Union
>>> get_origin(int | str)
<class 'types.UnionType'>
>>> get_origin(Optional[int])
typing.Union
>>> get_origin(int | None)
<class 'types.UnionType'>
```
I'm curious about how to update the test so that it works on both Python 3.9 and Python 3.10.
If you can point me in the right direction, I'll gladly update it.
This would fix #685.
=> Support both new and old style Union/Optional

docs/docs/guides/api-docs.md
I've added a section titled **Resolving the doc's url** to the **API Docs** page, detailing how to reverse a url for the api documentation view. This has been created in response to [issue 712](https://github.com/vitalik/django-ninja/issues/712). I was unable to find any reference to a name for the api docs view to use with Django's reverse feature.
[vitalik](https://github.com/vitalik) has pointed out that the view's name is _openapi-view_.
=> Added a section detailing how to reverse a url for the api docs page.

ninja/pagination.py, tests/test_openapi_schema.py
=> fix: allow default example to be included in pagination output in generated API docs.

ninja/orm/fields.py, tests/test_orm_metaclass.py, tests/test_orm_schemas.py
The more important purpose of this fix though, is that it changes the verbose_name to not be translated too early (see #646).
If the actual logical change isn't required, it's even simpler (but I think the smarter way  is more sensible).
=> Only title-case fields in schema if all lowercase verbose name

ninja/main.py
Without enabling the callable to take any # of inputs and return Any as the type, Pyright will complain with these two errors:
```
Type of "exception_handler" is partially unknown
Type of "exception_handler" is "(exc_class: Type[Exception]) -> ((...) -> Unknown)"Pylance[reportUnknownMemberType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)
Untyped function decorator obscures type of function; ignoring decoratorPylance[reportUntypedFunctionDecorator](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUntypedFunctionDecorator)
```
Hence, you need to disable those checks for this line. The typing adjustment I am advocating for fixes that!
```py
@api.exception_handler(  # pyright: ignore [reportUntypedFunctionDecorator, …
```
=> Enable exception_handler to handle Pyright's strict mode

ninja/files.py
`UploadedFile.__modify_schema__` has a `field` parameter that is not used in the method body, is typed as `Optional`, but still requires a value. Schema generation fails because of the value for this parameter not being provided.
=> Make optional field of UploadedFile optional

docs/docs/guides/authentication.md, ninja/operation.py, ninja/utils.py, tests/test_auth_async.py, tests/test_csrf_async.py
This PR introduces initial support for asynchronous authentication by allowing users to pass in async callables through the `auth` kwarg. The built-in authentication classes provided by this project remain synchronous-only.
Doesn't fully solve https://github.com/vitalik/django-ninja/issues/44, but it might be a good first step towards full async auth support.
=> Implement rudimentary support for async auth

docs/docs/guides/api-docs.md
Removes redundant curly bracket which makes it invalid.
=> Fix OpenAPI spec example in api-docs.md

.pre-commit-config.yaml
Currently, when trying to run any pre-commit hooks in Python 3.10, `poetry` crashes with the following log:
```bash
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/alxd/.cache/pre-commit/repords8_k88/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/alxd/.cache/pre-commit/repords8_k88
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata …
```
=> Replace pre-commit `flake8` and `isort` with `ruff`

.pre-commit-config.yaml
Continuation of https://github.com/vitalik/django-ninja/pull/805 :
> Ruff's pre-commit hook should be placed after other formatting tools, such as Black and isort, unless you enable autofix, in which case, Ruff's pre-commit hook should run before Black, isort, and other formatting tools, as Ruff's autofix behavior can output code changes that require reformatting.
From https://github.com/astral-sh/ruff-pre-commit .
=> Place pre-commit `ruff` before `black` because of its `autofix`

ninja/responses.py, tests/test_response.py
This would allow proper usage of enums in path parameters
Currently if you want to have an enum in the path, you would do this.
```
enum_value: SomeEnumClass = Path(...),
```
Which works fine until the request path includes an enum value that does not exist.
ie.
```
class SomeEnumClass(enum.Enum):
first: "first"
second: "second"
requests.get("some_path/third/other")
```
This would return a 500 instead of an expected 422 due to crashing in the JSONEncoder.
Returning and error
```
TypeError: Object of type SomeEnumClass is not JSON serializable"
```
=> Include Enum to NinjaJSONEncoder

ninja/errors.py, tests/test_errors.py
I'm using[ `loguru` ](https://github.com/Delgan/loguru) for logging and had hard time debugging `TypeError: ValidationError.__init__() missing 1 required positional argument: 'errors'` while calling `logger.exception` in Ninja `api.on_exception`. This is addressing the issue.
Fixes #822
=> #822 "ValidationError" and "HttpError" are not unpicklable

tests/main.py, tests/test_query.py
I had a bit of trouble figuring out list query parameters - possibly they could be a bit better documented in terms of needing to set them up with `Query(...)`?
While working this out I implemented a quick test for django-ninja's handling of list params, hopefully this is useful.
=> Add a test for list query params

ninja/operation.py
Address for a Warning during async-auth request.
detail is here https://github.com/vitalik/django-ninja/issues/44#issuecomment-1805733011
=> Suppress async-auth Warning "never awaited"

docs/docs/whatsnew_v1.md
Fix typo in whatsnew documetation.
1. async -> csrf
2. markdown break (hl does'nt work in MkDocs)
=> fix typo in whatsnew_v1.md

docs/docs/reference/csrf.md
=> More comprehensive documentation for CSRF protection

tests/test_auth_async.py
Fix this warning in the test suite:
```
test_auth_async.py::test_async_authenticate_method_in_sync_context
test_auth_async.py:142: PytestWarning: The test <Function test_async_authenticate_method_in_sync_context> is marked with '@pytest.mark.asyncio' but it is not an async function. Please remove asyncio marker. If the test is not marked explicitly, check for global markers applied via 'pytestmark'.
@pytest.mark.skipif(django.VERSION < (3, 1), reason="requires django 3.1 or higher")
```
=> Fix pytest.mark.asyncio warning

docs/src/tutorial/body/code01.py
**"filename"**: "docs/src/tutorial/body/code01.py"
**"warning_type"**: "Incompatible attribute type [8]"
**"warning_message"**: " Attribute `description` declared in class `Item` has type `str` but is used as type `None`.",
**"warning_line"**: 6
**"fix"**: "" instead of None
=> Attribute `description` declared has type `str` but is used as type None

tests/test_request.py
pytest assumes router function with test prefix as a test.. but it's not.
```
tests/test_request.py::test_schema
/envs/django-ninja/lib/python3.12/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but tests/test_request.py::test_schema returned 'ok', which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
```
=> Fix test warning

ninja/conf.py
Cleans up some of the documentation around pagination settings. Fixes documented default page size to match what's in the code and changes the description of `NINJA_PAGINATION_MAX_LIMIT` to more accurately reflect what the code does.
=> Update ninja conf docs

README.md
Updates the README to use the correct link to the test workflow badge, fixing the rendering error. I assumed it was best to use the `test_full` workflow rather than just `test` (which has the name "Test Coverage" in the badge), but happy to change to either. 
Currently -
After change -
=> Fix README.md test badge

ninja/filter_schema.py
This PR makes a minor typing improving to the `filter` method in `FilterSchema`
Right now, typing information for the queryset's model is lost since we return an arbitrary queryset. This PR uses a generic parameter to ensure typing information is not lost.
=> Minor Typing Improvement for `FilterSchema`

CONTRIBUTING.md, docs/docs/guides/input/form-params.md, docs/docs/guides/response/config-pydantic.md, docs/docs/guides/response/django-pydantic-create-schema.md, docs/docs/guides/response/index.md, docs/docs/motivation.md, docs/docs/proposals/index.md, docs/docs/whatsnew_v1.md, docs/mkdocs.yml
Generating the documentation produces a number of warnings, which could be disconcerting or confusing for first time contributors. This PR cleans up those warnings. 
It also:
- Adds "What's new in V1" to the documentation navigation.
- Cleans up some language in the contributors guide. 
Existing warnings:
```INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- whatsnew_v1.md
INFO    -  Doc file 'motivation.md' contains an absolute link '/guides/versioning/', it was left as is. Did you mean
'guides/versioning.md'?
INFO    -  Doc file 'motivation.md' contains an absolute link '/guides/response/#returning-querysets', it was left as is. Did you mean
'guides/response/index.md#returning-querysets'?
INFO    -  Doc file 'motivation.md' …
```
=> Cleanup documentation warnings

docs/docs/guides/response/index.md
close #1105 
Below `Empty responses` I placed a new headline `Error responses` which links the errors page.
=> docs(response): add link for error responses

ninja/pagination.py, tests/test_pagination.py
add `le=` parameter to LimitOffsetPagination.Input so the max input is visible and validated on the schema level.
Current implementation of limit is a little bit misleading - when `NINJA_PAGINATION_MAX_LIMIT` is set to 100 and limit in request is set to 1000 - the request is successful and only returns 100 items - see `LimitOffsetPagination.paginate_queryset`
```python 
limit: int = min(pagination.limit, settings.PAGINATION_MAX_LIMIT)
```
This is a little bit misleading behaviour and enforcing the limit on schema level can remove some confusion and will directly tell the consumer what the limit actually is.
**Warning - this is a breaking change for integrations which are using higher limit in request than it is set on the server.**
=> Update LimitOffsetPagination.Input schema

.github/workflows/test_full.yml, CONTRIBUTING.md, Makefile, pyproject.toml
Hi, this is my first PR to the project. Please let me know, if I missed anything.
This PR modernizes the ruff configuration to work with ruff >= v0.2.
It gets rid of these warnings:
```console
$ ruff ninja tests
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'per-file-ignores' -> 'lint.per-file-ignores'
All checks passed!
```
=> chore: modernize ruff config to work with ruff >= v0.2

docs/docs/guides/testing.md
Could also go the other way and do:
```
from ninja.testing import TestClient as NinjaTestClient
```
=> Fix TestClient name in testing docs

ninja/main.py
Fix typing for the exception handlers in `ninja.main`, which is currently leading to typing errors in my codebase due to the lack of generics.
=> Fix typing for Exception Handlers

ninja/decorators.py, ninja/files.py, ninja/main.py, ninja/orm/fields.py, ninja/params/__init__.py, ninja/signature/details.py, ninja/signature/utils.py, ninja/utils.py
For projects using Django Ninja that utilize [Pyright](https://github.com/microsoft/pyright), the typing for `decorate_view` leads to a `reportUntypedFunctionDecorator` error.
Let's take this example from the documentation:
```python
from django.views.decorators.cache import cache_page
@api.get("/test")
@decorate_view(cache_page(5)) # Untyped function decorator obscures type of function
def test_view(request):
return str(datetime.now())
```
By having `decorate_view` utilize generics, we can can avoid this. I also went about generally cleaning up the callable types, `Callable[..., Any]` is more descriptive than `Callable`. In Pyright the former would be preferred to avoid unknowns, as `Callable == Callable[..., Unknown]` instead of being `Any`. There have been times where I've imported …
=> Add Generic Typing for `decorate_view` to resolve Pyright Issues

docs/docs/guides/input/operations.md
- https://docs.python.org/3/library/http.html#http-methods
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
=> docs(operations): minor adjustments

docs/mkdocs.yml, docs/requirements.txt
Adds dark mode to docs. Also allows to use default system theme. Closes #1051.
Dark Mode:
Light Mode:
Auto Mode:
=> Add dark mode to ninja docs

docs/docs/guides/response/django-pydantic.md
Fixes: #1045
I believe the right thing to do here is to iterate over fields to patch and exclude all the unsupplied fields. Preceding documentation already shows how to use `fields_optional`, but it remains somewhat confusing what to do next.
=> Docs: Adds an example to show how exclude_unset works

ninja/schema.py
Fix Ninja schema typing by adding a dataclass transformer, as specified in [PEP 681](https://peps.python.org/pep-0681/). This transformer matches that of Pydantic's model metaclass.
Now, instead of Ninja schemas being typed as `**kwargs: Any`, one will get static type-checking on each field.
Fixes: https://github.com/vitalik/django-ninja/issues/1094, https://github.com/vitalik/django-ninja/issues/1050, https://github.com/vitalik/django-ninja/issues/1053
Example:
=> Fix Ninja Schema Typing

ninja/signature/utils.py
Closes #1203
I would be nice to have minor version upgrade after this
=> Fix ForwardRef._evaluate() missing 1 required keyword-only argument on python 3.12.4

ninja/schema.py, tests/test_schema.py
This PR addresses a bug reported here, where if validate_assignment is set to True on a schema, then Pydantic will correctly validate the new values, but the schema object will not persist the new value.
This is caused by the fact that [pydantic-core sets these new values on the object (once validated) directly on the object __ dict __](https://github.com/pydantic/pydantic-core/blob/0e6b377d2bef52e744deff22314269c8751f7b00/src/validators/dataclass.rs#L368). As it was, this means that the new value will be set onto the DjangoGetter object, rather than the schema object being validated.
Added an extra condition in the root validator of a Schema object that will call `handler` on the original values before the conversion to a DjangoGetter to ensure the new value is persisted properly on the …
=> Fix unchanging field bug when validate assignment true

ninja/router.py, tests/test_router_add_router.py
Added support for importing nested router with string path. This unifies behaviour with `api.add_router`:
```
api = NinjaAPI()
api.add_router("main", "myproject.app1.router")
router = Router()
router.add_router("nested", "myproject.app1.nested.router")
```
=> Support import string in router.add_router

docs/docs/guides/testing.md, ninja/testing/client.py, tests/test_test_client.py
Those changes let you set default headers for instances of NinjaClientBases, which are passed through all requests, unless overwritten.
Related to #664
=> Add default headers for NinjaClientBase instance

ninja/testing/client.py
Fixes https://github.com/vitalik/django-ninja/issues/1240
When using Python builtin functions for managing/consulting object attributes (`getattr` & `hasattr` for example), the mocked request always mocks and returns the mocked attribute value.
For example:
```python
hasttr(request, "field_name")  # Will always return True during testing, even if it's expected to be False
getattr(request, "field_with_dict", {}). # Will return a Mock object if field doesn't exist, causing a non-subscriptable exception during testing.
```
The issue originates during the instantiation of the mocked request in `ninja.testing.client._build_request`. There are 3 possible ways to instantiate the Mock object.
Setting django HttpRequest as spec when instantiating the Mock object, will restrict the instance to …
=> Fix issue when consulting request attributes while using mocked request

docs/docs/guides/input/filtering.md, ninja/filter_schema.py, tests/test_filter_schema.py
This MR allows creating custom filter type with pydantic to reuse across filter classes, by making the field_name implicit.
like:
```py
IContainsField = Annotated[Optional[str], Field(None, q='__icontains')]
class BookFilterSchema(FilterSchema):
name: IContainsField
=> Allow generic filter types

docs/docs/guides/testing.md, ninja/testing/client.py, tests/test_response.py
DRF lets you access a `data` attribute containing the deserialized data from the responses in tests.
Having the same kind of attribute (which, here, is computed and cached on the fly) would not only make writing tests slightly more comfortable, but would also make porting tests from DRF to Ninja a lot easier.
Related to #664
=> DRF-style data property for responses in tests

ninja/operation.py, tests/test_serialization_context.py
Pydantic starting with 2.7 added [support for context param in `model_dump` and `model_dump_json`](https://docs.pydantic.dev/latest/changelog/#new-features_2) allowing to pass arbitrary additional data into custom serializers.
Passing request in serialisation context may be useful in cases where customising serialisation is necessary.
=> Pass serialisation context to model_dump (fixes #1233)

docs/docs/guides/response/django-pydantic.md, ninja/__init__.py, ninja/patch_dict.py, ninja/utils.py, tests/test_patch_dict.py
PatchDict container allows to convert any schema into all-optional-fields schema and return a dict with only provided fields:
Usage example
```python
from ninja import PatchDict
class GroupSchema(Schema):
name: str
description: str
due_date: date
@api.patch("/patch/{pk}")
def modify_data(request, pk: int, payload: PatchDict[GroupSchema]):
obj = MyModel.objects.get(pk=pk)
for attr, value in payload.items():
setattr(obj, attr, value)
obj.save()
```
=> PatchDict util

ninja/pagination.py, tests/test_pagination.py
`make test-cov` is not at 100% on Python>=3.11 when executed locally.
Nothing is wrong with the pipeline as it is still using Python 3.9 but it is a minor incovenience during development.
It is due to the fact that the handling of `typing.Any` becomes unnecessary with this change in cpython: python/cpython#88690
This PR resolves this situation by adding a quick UT that is not so useful for Python<3.11 but covers that specific `try` - `except` block.
We may (or may not) also add support for Python>=3.11 in the coverage pipeline, in this PR or another one.
=> Fixed coverage on Python>=3.11

docs/docs/guides/testing.md, ninja/testing/client.py, tests/test_test_client.py
Hello,
I just made the `TestClient` accept an optional `COOKIES` parameter, just like it was already possible to pass `headers`.
I also updated the documentation.
Thanks!
=> Made TestClient accept COOKIES + documentation

docs/docs/guides/testing.md, tests/env-matrix/README.md, tests/test_pagination.py, tests/test_router_defaults.py
Added a small comment in the testing doc to call out to the user to import the router. Then just some other typo fixes I saw.
=> Small typo fixes and doc mention router import

ninja/responses.py
Should resolve #1334, validates #717 and add IPNetwork as serialisable.
We have been migrating an app from FastAPI to Django-Ninja and have been running into these serialisation issues.
=> Add IPNetwork and Url serialisation

.github/workflows/test_full.yml, ninja/openapi/schema.py, ninja/params/__init__.py, ninja/testing/client.py
Just updating the code
- by having executed `make fmt` using the already present `--preview` argument of ruff
- so the pipeline use the same `--preview` option to stay consistent
Otherwise I'm just surprised that there is a difference between the pipeline and the Makefile, I can just remove the `--preview` in the Makefile if needed, or you can close that PR.
=> Update code with `make fmt` and the pipeline to use the same `--preview` option of Ruff

docs/docs/guides/response/index.md
The "update_forward_refs" which is suggested a few times in the docs is deprecated.
Would it be a good idea to replace these with "model_rebuild"?
It is apparently deprecated since pydantic 2.0, and will be removed in 3.0.
Note that the methods update_forward_refs and model_rebuild are not quite equivalent: update_forward_refs currently delegates to model_rebuild but with force=True, whereas the default is False. It might be worth checking whether this substitution is completely safe, but it does seem probably safe.
=> Replace update_forward_refs with model_rebuild in docs

docs/docs/guides/throttling.md, ninja/throttling.py, tests/test_throttling.py
This pull request enhances the throttling functionality to support multi-period intervals, such as `5/30s`, `10/5m`, and `100/2h`. Previously, the throttling implementation only allowed single-period intervals (e.g., `5/s`, `100/d`), which limited the granularity and flexibility of rate limits.
The new implementation expands the allowed syntax for throttle rates to accommodate use cases requiring multi-unit periods, making it easier to define more precise rate limits.
While single-period intervals work for many scenarios, they lack flexibility for more complex use cases. For example:
* Higher granularity: A rate like `20/5m` (20 requests every 5 minutes) cannot be expressed with the current system.
* Short-term bursts: Rates like `50/2h` allow finer control over bursts without spanning a …
=> Support multi-period intervals in throttling

docs/docs/guides/errors.md, ninja/errors.py, ninja/main.py, ninja/operation.py, tests/test_body.py
`ninja.errors.ValidationError`s have some fundamental bugs and discard crucial error context (see https://github.com/vitalik/django-ninja/issues/1381). I've been working around these problems with monkeypatching in my own project.
This PR allows developers to access the missing error context in order to make much friendlier error messages than is currently possible with Django Ninja. It solves Problem 1 from https://github.com/vitalik/django-ninja/issues/1381 and partially addresses Problem 2.
Fixing the other problems I found will take more PRs and a larger discussion, but I think this PR makes the situation better.
Prior to this PR, users had access to `ninja.errors.ValidationError`s via `@api.exception_handler(ValidationError)`, but this has some problems:
1. It discards error context …
=> Allow Customizing Validation Errors

ninja/security/__init__.py, ninja/security/session.py, tests/test_auth.py
Add method to check is user either staff or superuser.
=> Add method to check is user either staff or superuser.

.github/workflows/test_full.yml
`ubuntu-latest` just swapped to Ubuntu 24, which drops support for Python 3.7. There should probably be a separate discussion about dropping about 3.7, but this will fix the problem for now.
=> CI: Use Ubuntu 22 for 3.7 support in tests

ninja/testing/client.py, tests/test_query.py
Currently, Django Ninja's client.get only supports query parameters directly embedded in the URL, such as `/customers/details/?name=fred&age=7` . 
However, it lacks support for passing query parameters as a separate dictionary like 
```python
c.get("/customers/details/", query_params={"name": "fred", "age": 7})
```
This pull request enhances the _build_request method to extract query parameters from the request_params dictionary, providing a more flexible and cleaner API for testing GET requests with query parameters. 
The implementation maintains backward compatibility with the existing URL-based approach while adding this new functionality.
Now we can implement code like this:
```python
from ninja.testing import TestClient
response = client.get("/customers/details/", …
```
=> Add query parameters in request_params for testing

ninja/compatibility/files.py, ninja/conf.py, ninja/operation.py, tests/test_files.py
This PR addresses a longstanding [Django issue](https://code.djangoproject.com/ticket/12635) where request.FILES is only populated when the request method is POST, ignoring file uploads for other HTTP methods.
While this behavior may have aligned with how browsers handled file uploads in the past, modern browsers and HTTP clients allow file uploads with any method.
This PR introduces a check for non-POST methods that accept file uploads. If such a request is detected, Django-Ninja will raise an error with a suggestion to enable a specific middleware that corrects this behavior by ensuring request.FILES is properly populated.
can be disabled with `settings.NINJA_FIX_REQUEST_FILES_METHODS = []`
CC @baseplate-admin  (https://github.com/baseplate-admin/ninja_put_patch_file_upload_middleware)
=> Fix for request.FILES Population on Non-POST Methods

ninja/signature/utils.py
Possible fix for #1424
but eval_type_lenient is deprecated and replacement seems have other set of args - still need to investigate all this dark magic
=> try fix with : schema crashes when paginated and from __future__ import annotations

ninja/pagination.py
django ninja is a good framework, when I work on the project, I found the pagination on async view is much lower than sync view for performance wise, like row 1 and row 3, so I have made some update for the pagination class.
| Type | Name                 | # Requests | # Fails | Average (ms) | Min (ms) | Max (ms) | Average size (bytes) | RPS  | Failures/s |
| ---- | -------------------- | ---------- | ------- | ------------ | -------- | -------- | -------------------- | ---- | ---------- |
| async with origin pagination  | /api/bff/trade       | 108        | 12      | 11294.07     | 5764     | 23045    | 38551.11             | 0.86 | 0.1        |
| async with new pagination change  | /api/bff/trade/async | 108        | 0       | 75.9         | 25       | 475      | 43370                | …
=> Improve Performance for Async Pagination

docs/docs/guides/response/config-pydantic.md, tests/test_openapi_schema.py, tests/test_response.py
The original `to_camel` implementation converts the `snake_case` string to `PascalCase` instead of `camelCase`.
This PR has been modified to correctly convert it to `camelCase`.
Since this function is for documentation purposes, I have implemented it as concise as possible without considering edge cases (such as acronym, numbers etc.).
I am unable to run just `make docs` due to an error related to `mkdocs-autorefs` (refs https://github.com/mkdocstrings/autorefs/issues/68). I tried to deal with this problem by changing the version, but could not solve it.
=> fix: to_camel implementation in docs and tests

tests/test_pagination.py
There was a typo in pagination tests.
The tests will be correct and independent of each other.
=> fix: typo in test

ninja/router.py, ninja/signature/details.py, ninja/signature/utils.py, tests/main.py, tests/test_misc.py, tests/test_path.py
Before django ninja shadowed django's uuid to be able to to get string value from url:
```python
@api.get('/some/{uuid:id}')
def some(request, id):
return {'id': id, 'type': str(type(id))}  # type=str
```
Now added custom converted `uuidstr`
```python
@api.get('/some/{uuidstr:id}')
def some(request, id):
```
django 6.0 will not allow shadowing 
addresses #1452 #1266
=> uuidstr url converter instead of shadowing django uuid

.github/workflows/test.yml, .github/workflows/test_full.yml, pyproject.toml
This PR adds support for Django 5.2 and Python 3.13:
- Updated GitHub Actions test matrix:
- Added Python 3.13
- Added Django `<5.3`
- Set default installed Django version to `>=5.2` in CI workflows
- Updated `pyproject.toml`:
- Added Python 3.13 and Django 5.2 to classifiers
- Set Django version range to `>=3.1, <6.0`
Keeps the project up to date with the latest stable versions of Python and Django.
=> Update CI and packaging for Django 5.2 and Python 3.13 support

ninja/openapi/schema.py, tests/test_openapi_extra.py
Fixes https://github.com/vitalik/django-ninja/issues/1505
Also helps with similar issues encountered in https://github.com/vitalik/django-ninja/issues/1192 and https://github.com/vitalik/django-ninja/issues/1515.
This ensures that when `openapi_extra` is set on an API route, and the dict contents conflict with a list element already assigned by Ninja's own generation, the list elements are combined.
Previously, whatever Ninja set got overwritten. This meant that in examples like my test case, the path parameter would be missing from the API spec.
=> fix: Merge openapi_extra list elements instead of overwrite
